### PR TITLE
#83: Bind null in object constructor

### PR DESCRIPTION
**Pull request by chrifpa**
Fixes https://github.com/hoodiehq/hoodie-account-client/issues/83

### CODE REVIEW

**Comment by gr2m** [comment]
very nice, LGTM! Thanks

ping @hoodiehq/maintainers :eyes: for 2nd review

**Comment by chrifpa** [comment]
Cool. Was just about to ask what the proper procedure was to mark a PR as ready for review :smile:

**Comment by HipsterBrown** [comment]
Well done @chrifpa! LGTM! :+1:

**Comment by HipsterBrown** [comment]
Successfully merged. :smile:

**Pull request merged**
