### PR TITLE
rename bearer to session

### PR DESCRIPTION
**Pull request by gr2m**
part of hoodiehq/hoodie#490

### CODE REVIEW

**Comment by HipsterBrown** [comment]
LGTM :+1:

**Comment by jameswestnz** [comment]
For consistency with other `authorization` prefixes (Bearer, Basic, etc, etc), should we be uppercasing the first "s" on session? I think it's minor, but was just curious..

Would be the same here if so: https://github.com/hoodiehq/hoodie-account-server/pull/161

**Comment by gr2m** [comment]
> For consistency with other authorization prefixes (Bearer, Basic, etc, etc), should we be uppercasing the first "s" on session?

That’s a good point, yeah, I think we should do that, I’ll update the PRs. Does it otherwise look good for you?

**Comment by jameswestnz** [comment]
Other than the possibility of uppercasing the s in `session`, LGTM 👍

**Comment by Charlotteis** [comment]
LGTM once `session` is changed to `Session`

**Comment by gr2m** [comment]
Thanks for the reviews team!

**Pull request merged**
