### PR TITLE
feat: emit update event on profile change

### PR DESCRIPTION
**Pull request by espy**

### CODE REVIEW

**Comment by Charlotteis** [comment]
LGTM ✨ 

deskbeers

**Comment by gr2m** [comment]
looking at it now

**Comment by gr2m** [comment]
The account `update` event currently does not pass the profile property

```js
account.on('update', function (account) {
  // account.profile is undefined
})
account.profile.update({foo: 'bar'})
```

It’s somewhat related to https://github.com/hoodiehq/hoodie-account-client/issues/107. Probably the simplest solution for both #107 and this PR is to always include profile everywhere. It might eventually become a performance issues with people start storing gazillions of data in account profiles, but until then we should be fine?

Any thoughts?

**Comment by gr2m** [comment]
never mind, this is not affected, profile is included in the update event, LGTM! Merging

**Pull request merged**
